# Generated by Django 3.0.3 on 2020-03-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body_mass_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bodymassindex',
            constraint=models.CheckConstraint(check=models.Q(value__gte=0), name='value_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='mainpersondata',
            constraint=models.CheckConstraint(check=models.Q(age__gte=18), name='age_gte_18'),
        ),
    ]
